package ru.raif.delivery.lib.error

enum class Error {
    INVALID_ARGUMENTS,
    NOT_ENOUGH_VOLUME,
    OCCUPIED,
    ORDER_NOT_FOUND,
    INVALID_ORDER_STATUS,
    NO_COURIERS_FOR_DELIVERY,
    ORDER_ALREADY_EXISTS,
    COURIER_NOT_FOUND,
    COURIER_HAS_NO_ORDER,
}