--liquibase formatted sql
--changeset ruaryb:2 logicalFilePath:2-add-events-table.sql
CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION
(
    ID               UUID NOT NULL,
    LISTENER_ID      VARCHAR(512) NOT NULL,
    EVENT_TYPE       VARCHAR(512) NOT NULL,
    SERIALIZED_EVENT VARCHAR(4000) NOT NULL,
    PUBLICATION_DATE TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    COMPLETION_DATE  TIMESTAMP(9) WITH TIME ZONE,
    PRIMARY KEY (ID)
);
